version: '3'
services:

  test-database:
    image: "postgres" # use latest official postgres version
    env_file:
      - ./.env # configure postgres
    volumes:
      - ./database-data:/var/lib/postgresql/data/ # persist data even if container shuts down
    ports:
      - 5432:5432
    # Set health checks to wait until postgres has started
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5

  test-server:
    build:
      context: .
      dockerfile: Dockerfile.test
    env_file:
      - ./.env
    depends_on: 
      - test-database
    volumes:
      - ./node:/usr/src/app/node
      - ./package.json:/usr/src/app/package.json
      - ./package-lock.json:/usr/src/app/package-lock.json

volumes:
  database-data: {} # named volumes can be managed easier using docker-compose
